### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [rui314/9cc#2]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [new_sb](https://github.com/rui314/9cc/blob/b1a0c5025612ca1fe0a30adfde29d0df6e249885/util.c#L62)
- [realloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Memory reallocation") ⇒ [vec_push](https://github.com/rui314/9cc/blob/b1a0c5025612ca1fe0a30adfde29d0df6e249885/util.c#L28)

**Comment by rui314** [comment]
Thank you for the suggestion, but I intentionally omit error checking for the memory exhaustion situation, because we cannot really handle such situation. If the memory is so tight that malloc can fail, the entire system becomes unstable (e.g. the kernel chooses a process to kill to free up some amount of memory). So, your program becomes unstable even if you correctly handle such situation. 9cc doesn't handle malloc failure, so it crashes with SEGV when malloc fails. That's fine. In practice, that won't cause any trouble.

I'm trying not to make 9cc bullet-safe. Rather, I trust people don't shoot us. That design choice greatly simplifies its code, as you probably can see.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by rui314** [comment]
You probably should unlearn these kind of "best practices". I'm trying to keep my code as simple as I can so that you don't really need any higher-level metaprogramming.

**Comment by elfring** [comment]
How do you think about to avoid that this software [can depend on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers.")?
