### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [rui314/9cc#3]
I suggest to reuse a higher level build system than [your current small make script](https://github.com/rui314/9cc/blob/b753d5e0e8964f454298c4b95236d0eb017de2c8/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by andrewchambers** [comment]
elfring ... those are pointless crap. you can practically build with gcc *.c .

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by andrewchambers** [comment]
@elfring it takes engineering discipline to only add dependencies when they are needed. there is no reason for them now, in fact any dependency *reduce* reliability, this whole exchange is just a distraction from the actual compiler work anyway...

**Comment by rui314** [comment]
This is not a big project at all, so you don't really need a sophisticated build system. Our current Makefile is satisfactory. Reducing dependency to external tools is an important design goal. Make is available everywhere, and people knows it. So is the shell. Other build systems are not. Anyways, 9cc is so experimental that I don't want to change that kind of thing at the moment. I'm focusing on code itself, and keep everything else "boring". That's intentional.
